name: metadent_checkin_app
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  easy_localization: ^3.0.2
  dio: ^5.3.0
  equatable: ^2.0.5
  freezed: ^2.4.1
  get_it: ^7.6.0
  google_fonts: ^4.0.4
  responsive_framework: ^0.1.9
  flutter_screenutil: ^5.7.0
  flutter_form_builder: ^9.1.0
  form_builder_validators: ^9.0.0
  freezed_annotation: ^2.4.1
  animations: ^2.0.7
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/translations/
 